version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  install:
# Install our python package before building the docs
    - method: pip
      path: .
sphinx:
  fail_on_warning: true

formats:
  - pdf
  - epub
